# Schedule

```{r echo=FALSE}
url <- "https://docs.google.com/spreadsheets/d/e/2PACX-1vSkRZqVLjOAamGk82cTXmUNTj2WLCmPK_r1qLGn8ixgNmOlgff6VbSe0IgR_2qjc_CNSaBdhFPLrfyX/pub?gid=731106475&single=true&output=csv"
df <- read.csv(url)
library(kableExtra)
```

```{r results="asis", echo=FALSE}
# columns to display
cols_to_display <- c("time", "type", "author", "title")
# section headers
ds <- c(
    "Wed. - Sep. 17, '25",
    "Thu. - Sep. 18, '25",
    "Fri. - Sep. 19, '25")
is <- split(seq(nrow(df)), df$day)
# column widths
ws <- paste0(100/length(cols_to_display), "%")
kbl(df[, cols_to_display], row.names=FALSE) |>
    kable_material(full_width=TRUE) |>
    column_spec(seq_along(cols_to_display), width=ws) |>
    row_spec(which(df$type == "Keynote"), background="lavender") |>
    row_spec(which(df$type %in% c("Break", "Lunch")), background="lightyellow") |>
    pack_rows(ds[1], min(is[[1]]), max(is[[1]])) |>
    pack_rows(ds[2], min(is[[2]]), max(is[[2]])) |>
    pack_rows(ds[3], min(is[[3]]), max(is[[3]])) |>
    cat()
```
